#!/usr/bin/env bash

# shellcheck source=/dev/null
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'

# shellcheck source=/dev/null
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

# shellcheck source=/dev/null
source <(k completion zsh)
