#!/usr/bin/env bash

CURRENT_FILE="$HOME/.zshrc.d/080_switch_kubeconfig"

switch_kc() {
  if [[ -z $1 ]]; then
      export CONTEXT=""
  else
      export CONTEXT="-$1"
  fi
  sed -i '' "/^export/d" $CURRENT_FILE
  
  export KUBECONFIG="$HOME/.kube/config$CONTEXT"
  KUBECGG_CMD="export KUBECONFIG=\"$HOME/.kube/config$CONTEXT\""
  echo $KUBECGG_CMD >> $CURRENT_FILE
}

list_kc() {
  CURRENT=$(echo $KUBECONFIG | sed -e 's/^.*config-//')
  for i in $(ls ~/.kube/config*); do

    CFG=$(echo $i | sed -e 's/^.*config-//')
    if [[ "$CFG" = "$CURRENT" ]]; then
      echo "$(tput bold)* $CFG$(tput sgr0)"
    else
      echo "  $CFG"
    fi
  done
}

current_kc() {
  echo $KUBECONFIG | sed -e 's/^.*config-//'
}

export KUBECONFIG="/Users/pyaillet/.kube/config-scaleway"
